data: Checkerboard
condition: Radial
load_path: None
batch_size: 128
lr: 1e-4
nepochs: 32
gclip: 5
nstack: 1
nblocks: 15
nnodes: 128
nbins: 10
activation: relu
coupling: False
coupling_width: 32
coupling_depth: 2