output:
  save_dir: global/home/users/rrmastandrea/flows4flows/writeup2/
  name: science_L1

general:
  data_dim: 5
  ncond: 1
  cuda_slot: 0
  
base_dist:
  plot: True
  left:
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup2/science/base_left/epoch_59.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 60
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

  right:
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup2/science/base_right/epoch_59.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 60
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 64
  gclip: 5
  nstack: 8
  nblocks: 3
  nnodes: 128
  nbins: 8
  activation: relu
  penalty: l1
  penalty_weight: 0.05
  anneal: 0
  direction: alternate
  identity_init: 0

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .