output:
  save_dir: /global/home/users/rrmastandrea/flows4flows/writeup2/
  name: test

general:
  data_dim: 2
  n_points: 1e5
  ncond: 1
  cuda_slot: 1

base_dist:
  condition: rotation
  base_data: fourcircles
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 2
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 128
  nbins: 8
  activation: relu
  coupling: False
  coupling_width: 32
  coupling_depth: 2

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 2
  flow4flow: delta
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 128
  nbins: 8
  activation: relu
  coupling: False
  coupling_width: 32
  coupling_depth: 2
  penalty: None
  penalty_weight: 1
  anneal: 1
  identity_init: 1

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
