output:
  save_dir: ./flows4flows/
  name: writeup

general:
  data_dim: 2
  n_points: 1e6
  ncond: 1
  condition: rotation

base_dist:
  plot: True
  left:
    data: checkerboard
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup/checkerboard_to_circles_cond_1e6/base_left/epoch_31.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 32
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

  right:
    data: fourcircles
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup/checkerboard_to_circles_cond_1e6/base_right/epoch_31.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 32
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 12
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 128
  nbins: 8
  activation: relu
  penalty: None
  penalty_weight: 1
  anneal: 1
  direction: alternate

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .