output:
  save_dir: ./flows4flows/
  name: test

general:
  data_dim: 5
  ncond_base: 1
  ncond: 1

base_dist:
  plot: False
  batch_size: 128
  left:
    load_path: None
    lr: 1e-3
    nepochs: 20
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu
    coupling: False
    coupling_width: 32
    coupling_depth: 2


top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 20
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 128
  nbins: 8
  activation: relu
  coupling: False
  coupling_width: 32
  coupling_depth: 2
  penalty: None
  penalty_weight: 1
  anneal: 1
  direction: forward

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
