output:
  save_dir: /global/home/users/rrmastandrea/flows4flows/writeup2/
  name: fourcircles_checkerboard_nocond_inv
  
general:
  data_dim: 2
  n_points: 1e6
  ncond: 0
  cuda_slot: 0

base_dist:
  left:
    data: fourcircles
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup2/fourcircles_fourcircles_nocond_f4f/base_left/epoch_59.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 60
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

  right:
    data: checkerboard
    load_path: /global/home/users/rrmastandrea/flows4flows/writeup2/checkerboard_checkerboard_nocond_f4f/base_right/epoch_59.pt
    batch_size: 128
    lr: 1e-4
    nepochs: 60
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 64
  flow4flow: discretebase
  iteration_steps: 5
  gclip: 5
  nstack: 8
  nblocks: 3
  nnodes: 128
  nbins: 8
  activation: relu
  penalty: None
  penalty_weight: 1
  anneal: 0
  direction: inverse
  identity_init: 0

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .