load_path: None
batch_size: 256
lr: 5e-4
nepochs: 50
flow4flow: discretebasecondition
direction: forward
iteration_steps: 5
gclip: 5
nstack: 2
nblocks: 8
nnodes: 32
nbins: 10
activation: relu
coupling: False
coupling_width: 32
coupling_depth: 2
penalty: None
penalty_weight: 1
anneal: 1